// Generated by CoffeeScript 1.9.3
var GemnasiumClient, https;

https = require('https');

GemnasiumClient = (function() {
  function GemnasiumClient() {
    this._token = process.env.GEMNASIUM_TOKEN;
    if (!this._token) {
      throw new Error('No GEMNASIUM_TOKEN environment variable set');
    }
    this._slug = process.env.GEMNASIUM_PROJECT_SLUG;
    if (!this._slug) {
      throw new Error('No GEMNASIUM_PROJECT_SLUG environment variable set');
    }
  }

  GemnasiumClient.prototype.alerts = function(cb) {
    var options;
    options = {
      hostname: 'api.gemnasium.com',
      path: "/v1/projects/aaaa" + this._slug + "/alerts",
      auth: "x:" + this._token
    };
    return https.get(options, function(res) {
      var body;
      body = '';
      res.setEncoding('utf8');
      res.on('data', function(chunk) {
        return body += chunk;
      });
      return res.on('end', function() {
        var e, parsed;
        parsed = null;
        try {
          parsed = JSON.parse(body);
        } catch (_error) {
          e = _error;
          console.log("body: ", body);
          return cb(e);
        }
        if (res.statusCode !== 200) {
          return cb(new Error(parsed.message));
        }
        if (!parsed) {
          parsed = [];
        }
        return cb(void 0, parsed);
      });
    }).on('error', function(e) {
      return cb(e);
    });
  };

  return GemnasiumClient;

})();

module.exports = GemnasiumClient;
